package net.suteren.medicomp.domain;

public enum Type {
	TEMPERATURE, DIOPTRY, BLOOD_GROUP, ALLERGY, CONTRAINDICATION, WEIGHT, HEIGHT, HEARTBEAT, PRESSURE, MEDICATION, INTERVENTION, ACCIDENT, DISEASE, FEELING;
}
